### ISSUE TITLE
resetear contador de trials

### ISSUE THREAD

**Issue by yagui** [yagui/sphere-training#41]
Al detener (stop, no pausa) el entrenemiento, y luego volver a iniciar, aparentemente no se borran los valores acumulados de cantidad de trials y cantidad de trials exitosos, ya que la estadística calculada parece utilizar los valores previos.

snip del log con comentarios
2015/01/19 15:53:24.693 - training - INFO - ===============================================
2015/01/19 15:53:24.694 - training - INFO - Start training
2015/01/19 15:53:47.58 - training - INFO - Starting trial:0
...
2015/01/19 15:53:56.63 - training - INFO - End trial:0 (porque empieza con el trial 0??)
...
2015/01/19 15:53:56.63 - training - INFO - Trial not successful
2015/01/19 15:53:56.64 - training - INFO - Success rate: '0.0'
2015/01/19 15:53:56.668 - training - INFO - Starting trial:1
...
2015/01/19 15:54:06.681 - training - INFO - End trial:1
...
2015/01/19 15:54:06.681 - training - INFO - Trial not successful
2015/01/19 15:54:06.681 - training - INFO - Success rate: '0.0'
2015/01/19 15:54:13.21 - training - INFO - Starting trial:2
....
2015/01/19 15:54:23.32 - training - INFO - End trial:2
...
2015/01/19 15:54:23.32 - training - INFO - Trial not successful
2015/01/19 15:54:23.33 - training - INFO - Success rate: '0.0'
2015/01/19 15:54:29.117 - training - INFO - Starting trial:3
...
2015/01/19 15:54:39.128 - training - INFO - End trial:3
...
2015/01/19 15:54:39.128 - training - INFO - Trial successful
2015/01/19 15:54:39.129 - training - INFO - Success rate: '25.0' 
2015/01/19 15:54:39.179 - training - INFO - Starting trial:4
...
2015/01/19 15:55:13.60 - training - INFO - training stopped. (ACA SE DETIENE EL ENTRENAMIENTO)
2015/01/19 15:55:13.60 - training - INFO - Success rate: 42.8
2015/01/19 15:55:13.60 - training - INFO - Movement trials: 3 / 7
...
2015/01/19 15:55:35.871 - training - INFO - Starting trial:0 (LUEGO VUELVE A EMPEZAR)
2015/01/19 15:55:44.879 - training - INFO - End trial:0
2015/01/19 15:55:44.879 - training - INFO - Trial not successful
2015/01/19 15:55:44.879 - training - INFO - Success rate: '0.0'
2015/01/19 15:55:46.36 - training - INFO - Starting trial:1
2015/01/19 15:55:56.53 - training - INFO - End trial:1
2015/01/19 15:55:56.54 - training - INFO - Trial not successful
2015/01/19 15:55:56.54 - training - INFO - Success rate: '0.0'
2015/01/19 15:55:59.25 - training - INFO - Starting trial:2
2015/01/19 15:56:01.37 - training - INFO - Reward not given because trial was not successful
2015/01/19 15:56:01.37 - training - INFO - Start inter-trial delay
2015/01/19 15:56:01.591 - training - INFO - training stopped. (ACA SE VUELVE A DETENER)
2015/01/19 15:56:01.591 - training - INFO - Success rate: 0.0
2015/01/19 15:56:01.591 - training - INFO - Movement trials: 3 / 10 (en el segundo entrenamiento sumo los exitos y fracasos del entrenamiento anterior, ademas está contando el ultimo trial)

**Comment by alfredoivan** [comment]
Arreglado.
Se agregaron excepciones cuando se finaliza un entrenamiento con un trial en ejecución , prematuramente.

(empieza en trial 1 ahora)

**Comment by alfredoivan** [comment]
(no volvió a reincidir desde que se arregló)
