### ISSUE TITLE
El trial se cuenta antes de que termine

### ISSUE THREAD

**Issue by yagui** [yagui/sphere-training#42]
En las estadisticas el trial se cuenta antes de que termine. Eso hace que cuando se detiene el entrenamiento, el trial que se estaba llevando a cabo no esta terminado y se usa para la estadistica

**Comment by alfredoivan** [comment]
Arreglado, parecido a issue anterior.

**Comment by alfredoivan** [comment]
(no hubo reincidencia desde que se arregló)
