### ISSUE TITLE
Modos de entrenamiento

### ISSUE THREAD

**Issue by alfredoivan** [yagui/sphere-training#47]
Poner un checkbox "modo pavlov" que haga lo siguiente (c.clásico):
tono => gota
≡ a mvnt / still siempre exitoso (poner boolean)

Este modo debe deshabilitar algunos elementos gráficos, como movement threshold, etc.

Poner checkbox "modo skinner" (c.o.) que haga lo siguiente:
d(tono) = 0.0 s
ITI= 0 s
camina => gota 
debe deshabilitar elementos gráficos relacionados con tono (duración, frequencia)

**Comment by alfredoivan** [comment]
Luego de discutir el tema se hacen las siguientes correcciones en base a teoría cognitiva:

modo pavlov:
  tono , luego gota

modo skinner:
  tono, detecta caminar, gota si camina

modo "sólo detección de movimiento":
  detecta caminar, gota si camina

**Comment by yagui** [comment]
El modo skinner es sin tono
skinner: detecta caminar, gota si camina

operante: tono, detecta caminar, gota si camina

**Comment by alfredoivan** [comment]
pavlov:
     tono, gota

skinner:
     camina => gota

operante:
     tono, camina=> gota

discriminación:
     tono, quieto/camina => gota

**Comment by alfredoivan** [comment]
(modo skinner: ponerle que sea solamente tono 1)

**Comment by alfredoivan** [comment]
(hecho)
