### ISSUE TITLE
Archivos de configuracion

### ISSUE THREAD

**Issue by yagui** [yagui/sphere-training#54]
Todos los archivos de configuracion, si no existen, deben generarse automaticamente a partir del .py.examples

**Comment by alfredoivan** [comment]
Hay que chequear uno por uno si se generan apropiadamente.
Falta agregar al repositorio:
training/configs/config_Discr.py
training/configs/config_Ocond.py
training/configs/config_Skinner.py
training/configs/config_Pavlov.py

(para esto, tiene que andar la funcionalidad de elegir entre diferentes tipos de entrenamiento durante el entrenamiento)

**Comment by alfredoivan** [comment]
Se generan los archivos correspondientes al iniciar el programa por primera vez.
